{
 "title": "ML API Dashboard",
 "description": "Machine learning-specific metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Model Versions",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(live_model, live_version, shadow_model, shadow_version, version)(model_version_details_info\n* on (instance, job) group_left(version)\npython_info)",
     "legendFormat": "{{model_version}}"
    }
   ]
  },
  {
   "title": "Average House Price Prediction Amount (USD)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate(house_price_prediction_dollars_sum{job=\"ml_api\"}[1m])) / sum (rate(house_price_prediction_dollars_count{job=\"ml_api\"}[1m]))",
     "legendFormat": "Average Prediction Amount ($)"
    }
   ]
  },
  {
   "title": "Average House Price Prediction Rate (/second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(house_price_prediction_dollars_count{job=\"ml_api\"}[1m])",
     "legendFormat": "Average Prediction Rate"
    }
   ]
  },
  {
   "title": "Standard Error of the Mean (SEM)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(house_price_gauge_dollars[1m])",
     "legendFormat": "AVG"
    },
    {
     "expr": "stddev_over_time(house_price_gauge_dollars[1m])",
     "legendFormat": "STD"
    },
    {
     "expr": "stddev_over_time(house_price_gauge_dollars[1m]) / (sqrt(count_over_time(house_price_prediction_dollars_count[1m])))",
     "legendFormat": "SEM"
    }
   ]
  },
  {
   "title": "Standard Score (Z-Score)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(avg_over_time(house_price_gauge_dollars[1m])  - avg_over_time(house_price_gauge_dollars[1w])) /  (stddev_over_time(house_price_gauge_dollars[1w]))",
     "legendFormat": "Z-Score"
    }
   ]
  },
  {
   "title": "Min Prediction",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "house_price_gauge_dollars", "legendFormat": "Average Prediction Amount ($)" }
   ]
  },
  {
   "title": "Max Prediction",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "house_price_gauge_dollars", "legendFormat": "Average Prediction Amount ($)" }
   ]
  }
 ]
}