version: '3.8'
services:
  ml_api:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: model_api
    expose:
      - 5000
    ports:
      - "5001:5000"   # expose webserver to localhost host:container
    command: bash -c "make run-service-wsgi"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/  # path on the host, relative to the compose file
      - prometheus_data:/prometheus  # named volume
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    expose:
      - 9090
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"

volumes:
  prometheus_data:
  grafana_data: